export const Problem_Table = [
  'Revenge for Unjust killing',
  'Apprehend / Bounty Hunt - Crime committed, criminal disappeared',
  'Retrieval of lost item',
  'Repel / Sabotage / Deceive / Sabotage / Extort / Entrap - Tyrant(s) threaten town / business / population (monster / humanoid) ',
  'Investigate / Solve Environmental disturbance / Strange Weather / Infestation / Plague ',
  'Investigate / Lift curse / destroy magic - Magical chaos / Curse',
  'Rescue / Recover - Kidnapping / Hostage situation ',
  'Rescue lost adventurer',
  'Explore / Discover Something is rumoured, but undiscovered (Artefact, legendary place)',
  'Loot - Riches rumoured within secure, guarded place ',
  'Repel / Divert - Invasion ',
  'Spy / Gather information Person suspected of something ',
  'Transport / smuggle / escort - Important item / message / person needs transporting ',
  'Waylay / Hijack Nefarious / dangerous item being transported ',
  'Find / Destroy Dangerous item exposed / up for grabs ',
  'Investigate / Implicate / Incriminate / Expose - Corrupt noble ',
  'Transport supplies Commodity shortage (goods, workforce)',
  'Research / Explore / Decode - Mystery unresolved ',
  'Survive being thrown into life-threatening situation (environmental or otherwise)',
  'Protect, eliminate threat  Worthy creature’s life threatened (humanoid / animal / monster)',
  'Prevent Execution of innocent party planned ',
  'Break Siege (anything from a small party of goblins surrounding a farmhouse to an army of Imperial Blades surrounding a city!) ',
  'Negotiate / Prepare / Mediate / Participate - Huge battle about to erupt',
  'Visit / Gain boon - Spiritually beneficial place rumoured ',
  'PC hired to conceal evidence / Return item / Placate - Foolish individual committed innocent blunder ',
];
