import { armorSchema } from '..';

export const pants: armorSchema = {
  techLevel: 0,
  code: 'pants',
  zones: [['leftLeg', 'rightLeg']],
  matchingArmorTypes: [
    'layredClothLight',
    'cane',
    'paddedCloth',
    'hardenedLeatherMedium',
    'hardenedLeatherHeavy',
    'brigandineMedium',
    'brigandineHeavy',
    'mailFine',
    'straw',
    'layeredLeatherHeavy',
    'layeredLeatherMedium',
    'layeredClothHeavy',
    'jackOfPlates',
    'leatherHeavy',
    'leatherMedium',
    'mailAndPlates',
    'scaleLight',
    'scaleMedium',
    'scaleHeavy',
    'mailLight',
    'mailHeavy',
    'segmentedPlateLight',
    'segmentedPlateHeavy',
    'layeredClothMedium',
    'segmentedPlateMedium',
    'papperProofed',
    'layeredLeatherLight',
    'mailJousting',
    'plateLight',
    'plateMedium',
    'plateHeavy',
    'brigandineLight',
  ],
};
