export const architectureTable = [
  'Statue',
  'Series of alcoves',
  'Fountain',
  '1d4 Pools',
  'Hole in floor',
  'Underground terrarium',
  'Pillars along each side. Anything hiding there?',
  'Catacombs',
  'Puzzle of some sort (int check required)',
  'Sacrificial plinth',
  'Temple / shrine',
  'Guard post',
  'Trapdoor with ladder',
  'Underground stream',
  'Natural cavern',
  'Ventilation shaft',
  'Crystal growth',
  'Campsite, abandoned',
  'Portal. Takes you to another, random part of the dungeon',
  'Edible Fungi / Moss Farm',
];
