import { random } from 'lodash';
import { DefaultCombinedGenerator } from '../defaultCombinedGenerator';

const aquatic = [
  'Quipper ',
  'Sea Horse ',
  'Crab ',
  'Octopus',
  'Dolphin ',
  'Merfolk ',
  'Giant Crab ',
  'Constrictor Snake ',
  'Steam Mephit ',
  'Kuo-toa ',
  'Reef Shark ',
  'Giant Seahorse ',
  'Sahuagin ',
  'Crocodile ',
  'Giant Octopus ',
  'Seaspawn ',
  'Swarm of Quippers ',
  'Kuo-toa whip ',
  'Giant Constrictor',
  'Snake ',
  'Hunter Shark ',
  'Merrow ',
  'Sahuagin Priestess ',
  'Sea Hag ',
  'Deep Scion ',
  'Killer Whale ',
  'Giant Shark ',
  'Sahuagin Baron ',
  'Water Elemental ',
];
const coastal = [
  'Lizard ',
  'Eagle ',
  'Rat ',
  'Crab ',
  'Scorpion ',
  'Blood Hawk ',
  'Bandit ',
  'Poisonous Snake ',
  'Tribal Warrior ',
  'Giant Crab ',
  'Guard ',
  'Kobold ',
  'Merfolk ',
  'Stirge ',
  'Dimetrodon ',
  'Giant Lizard ',
  'Giant Wolf Spider ',
  'Pseudodragon ',
  'Tortle ',
  'Winged Kobold ',
  'Sahuagin ',
  'Scout ',
  'Skulk ',
  'Giant Eagle ',
  'Giant Toad ',
  'Harpy ',
  'Sea Spawn ',
  'Bandit Captain ',
  'Berserker ',
  'Griffon ',
  'Merrow ',
  'Ogre ',
  'Sahuagin Priestess ',
  'Seahag ',
  'Quetzalcoatlus ',
  'Deep Scion ',
  'Manticore ',
  'Merrenoloth ',
  'Vampiric Mist ',
  'Veteran ',
  'Banshee ',
  'Orc War Chief ',
  'Sahuagin Baron ',
  'Water Elemental ',
  'Cyclops ',
  'Kuo-toa Archpriest ',
  'Water Elemental',
  'Myrmidon',
  'Kuo-toa Archpriest ',
];
const desert = [
  'Lizard ',
  'Hyena ',
  'Jackal ',
  'Scorpion ',
  'Vulture ',
  'Giant Fire Beetle ',
  'Bandit ',
  'Flying Snake ',
  'Kobold ',
  'Poisonous Snake ',
  'Tribal Warrior ',
  'Young Kruthik ',
  'Constrictor Snake ',
  'Giant Lizard ',
  'Giant Poisonous Snake ',
  'Giant Wolf Spider ',
  'Pseudodragon ',
  'Winged Kobold ',
  'Dust Mephit ',
  'Firenewt Warrior ',
  'Gnoll ',
  'Hobgoblin ',
  'Jackalwere ',
  'Scout ',
  'Swarm of Insects ',
  'Gnoll Hunter ',
  'Death Dog ',
  'Firenewt Warlock of',
  'Imix ',
  'Giant Hyena ',
  'Giant Spider ',
  'Giant Toad ',
  'Giant Vulture ',
  'Half Ogre ',
  'Meazel',
  'Stone Cursed',
  'Thri-keen ',
  'Yuan-ti Pureblood ',
  'Vargouille ',
  'Adult Kruthik',
  'Guard Drake ',
  'Bandit Captain ',
  'Berbalang',
  'Berserker ',
  'Giant Constrictor',
  'Snake ',
  'Gnoll Pack Lord ',
  'Ogre ',
  'Yuan-ti Broodguard ',
  'Ogre Zombie ',
  'Giant Scorpion ',
  'Hobgoblin Captain ',
  'Leucrotta ',
  'Mummy ',
  'Phase Spider ',
  'Wight ',
  'Yuan-ti Mallison ',
  'Bearded Devil ',
  'Couatl ',
  'Dybbuk',
  'Gnoll Fang of',
  'Yeenoghu ',
  'Lamia ',
  'Weretiger ',
  'Yuan-ti Mind',
  'Whisperer',
  'Yuan-ti Nightmare',
  'Speaker',
  'Stone Defender',
  'Air Elemental ',
  'Kruthik Hive Lord ',
  'Fire Elemental ',
  'Revenant ',
  'Tanarukk ',
  'Spawn of Kyuss ',
  'Tlincalli ',
  'Yuan-ti Pitmaster ',
  'Cyclops ',
  'Hobgoblin Warlord ',
  'Medusa ',
  'Young Brass Dragon ',
  'Lost Sorrowsworn ',
  'Yuan-ti',
  'Abomination ',
];
const dungeon = [
  'Cranium Rat  133',
  'Crawling Claw ',
  'Giant Fire Beetle  325',
  'Homunculus ',
  'Lemure ',
  'Myconid Sprout ',
  'Rat ',
  'Scorpion ',
  'Shrieker  138',
  'Spider  337',
  'Boggle ',
  'Flumph ',
  'Giant Rat ',
  'Kobold ',
  'Manes ',
  'Monodrone ',
  'Neogi Hatchling ',
  'Poisonous Snake ',
  'Slaad Tadpole ',
  'Stirge ',
  'Xvaart ',
  'Young Kruthik ',
  'Deep Rothe ',
  'Derro ',
  'Drow ',
  'Giant Bat ',
  'Giant Centipede ',
  'Giant Lizard ',
  'Giant Poisonous',
  'Snake ',
  'Goblin ',
  'Grimlock ',
  'Kobold Inventor ',
  'Kuo-toa ',
  'Male Steeder ',
  'Oblex Spawn ',
  'Swarm Of Bats ',
  'Troglodyte ',
  'Violet Fungus ',
  'Winged Kobold ',
  'Wretched',
  'Sorrowsworn ',
  'Chitine ',
  'Darkling ',
  'Darkmantle ',
  'Firenewt Warrior ',
  'Gas Spore ',
  'Gazer ',
  'Gray Ooze ',
  'Hobgoblin ',
  'Magma Mephit ',
  'Myconid Adult ',
  'Orc ',
  'Orc Nurtured One of',
  'Yurtrus ',
  'Piercer ',
  'Rust Monster ',
  'Scout ',
  'Shadow ',
  'Skulk ',
  'Svirfneblin ',
  'Swarm of Insects ',
  'Swarm of Rot Grubs ',
  'Bugbear ',
  'Choker ',
  'Duergar ',
  'Female Steeder ',
  'Fire Snake ',
  'Firenewt Warlock',
  'of Imix ',
  'Ghoul ',
  'Giant Spider ',
  'Quaggoth Spore',
  'Servant ',
  'Giant Toad ',
  'Goblin Boss ',
  'Half Ogre ',
  'Kobold',
  'Dragonshield ',
  'Kobold Scale',
  'Sorcerer ',
  'Kuo-toa Whip ',
  'Maw Demon ',
  'Meazel ',
  'Nilbog ',
  'Vargouille ',
  'Xvart Warlock of',
  'Raxivort ',
  'Adult Kruthik ',
  'Carrion',
  'Crawler ',
  'Darkling Elder ',
  'Duergar',
  'Hammerer ',
  'Duergar',
  'Kavalrachni ',
  'Duergar Mind',
  'Master ',
  'Duergar Stone',
  'Guard ',
  'Duergar',
  'Xarrorn ',
  'Gargoyle ',
  'Gelatinous',
  'Cube ',
  'Ghast ',
  'Giant',
  'Constrictor',
  'Snake',
  'Gibbering',
  'Mouther ',
  'Grick ',
  'Guard Drake ',
  'Intellect',
  'Devourer ',
  'Mimic ',
  '61-64',
  'Minotaur',
  'Skeleton ',
  'Nothic ',
  'Ochre Jelly ',
  'Ogre ',
  'Orc Claw of',
  'Luthic ',
  'Orc Eye of',
  'Gruumsh ',
  'Orc Hand of',
  'Yurtrus ',
  'Orog ',
  'Quaggoth ',
  'Yuan-ti',
  'Broodguard ',
  'Cave Fisher ',
  'Choldrith ',
  'Derro Savant ',
  'Doppelganger ',
  'Duergar Screamer ',
  'Flail Snail ',
  'Grell ',
  'Hell Hound ',
  'Hobgoblin Captain ',
  'Hook Horror ',
  'Minotaur ',
  'Neogi ',
  'Orc Red Fang of',
  'Shargaas ',
  'Phase Spider ',
  'Quaggoth Thonot ',
  'Slithering Tracker ',
  'Spectator ',
  'Trapper ',
  'Vampiric Mist ',
  'Wight ',
  'Babau ',
  'Barghest ',
  'Black Pudding ',
  'Bone Naga ',
  'Chuul ',
  'Ettin ',
  'Flameskull ',
  'Ghost ',
  'Neogi Master ',
  'Orc Blade of Ilneval ',
  'Yuan-ti Mind',
  'Whisperer ',
  'Yuan-ti Nightmare',
  'Speaker ',
  'Adult Oblex ',
  'Beholder Zombie ',
  'Drow Elite',
  'Warrior ',
  'Earth Elemental ',
  'Kruthik Hive',
  'Lord ',
  'Mindwitness ',
  'Otyugh ',
  'Roper ',
  'Salamander ',
  'Spawn of Kyuss ',
  'Swarm of',
  'Cranium Rats ',
  'Tanarukk ',
  'Troll ',
  'Umber Hulk ',
  'Vampire Spawn ',
  'Wraith ',
  'Xorn ',
  'Yuan-ti Pit',
  'Master ',
  'Bodak ',
  'Chimera ',
  'Cyclops ',
  'Drider ',
  'Duergar Warlord ',
  'Gauth ',
  'Hobgoblin Warlord ',
  'Kuo-toa Archpriest ',
  'Bodak ',
  'Chimera ',
  'Cyclops ',
  'Drider ',
  'Duergar Warlord ',
  'Gauth ',
  'Hobgoblin Warlord ',
  'Kuo-toa Archpriest ',
];
const forest = [
  'Awakened Shrub ',
  'Baboon ',
  'Badger ',
  'Cat ',
  'Deer ',
  'Hyena ',
  'Owl ',
  'Weasel ',
  'Goat ',
  'Spider ',
  'Bandit ',
  'Blood Hawk ',
  'Boggle',
  'Flying Snake ',
  'Giant Rat ',
  'Giant Weasel ',
  'Guard ',
  'Kobold ',
  'Mastiff ',
  'Poisonous',
  'Snake ',
  'Stirge ',
  'Tribal Warrior ',
  'Twig Blight ',
  'Cultist ',
  'Noble ',
  'Blink Dog ',
  'Boar ',
  'Constrictor Snake ',
  'Giant Badger ',
  'Giant Bat ',
  'Giant Frog ',
  'Giant Lizard ',
  'Giant Owl ',
  'Giant Poisonous',
  'Snake ',
  'Giant Wolf Spider ',
  'Gnoll Witherling',
  'Goblin ',
  'Grung',
  'Kenku ',
  'Kobold Inventor',
  'Needle Blight ',
  'Panther ',
  'Pixie ',
  'Pseudodragon ',
  'Sprite ',
  'Swarm of Ravens ',
  'Vegepygmy',
  'Winged Kobold ',
  'Wolf ',
  'Ape ',
  'Black Bear ',
  'Darkling',
  'Giant Wasp ',
  'Gnoll ',
  'Gnoll Hunter',
  'Hobgoblin ',
  'Lizardfolk ',
  'Orc ',
  'Orc Nurtured One',
  'of Yurtrus',
  'Satyr ',
  'Scout ',
  'Skulk',
  'Swarm of Insects ',
  'Vine Blight ',
  'Worg ',
  'Bronze Scout ',
  'Bugbear ',
  'Choker ',
  'Dire Wolf ',
  'Dryad ',
  'Giant Spider ',
  'Giant Toad ',
  'Gnoll Flesh Gnawer ',
  'Goblin Boss ',
  'Grung Wildling ',
  'Half Ogre ',
  'Harpy ',
  'Kobold Dragonshield ',
  'Kobold Scale Sorcerer ',
  'Meazel ',
  'Nilbog ',
  'Quickling ',
  'Thorny ',
  'Young Faerie Dragon ',
  'Yuan-ti Pureblood ',
  'Adult Faerie',
  'Dragon ',
  'Ankheg ',
  'Awakened Tree ',
  'Bandit Captain ',
  'Berserker ',
  'Centaur ',
  'Darkling Elder ',
  'Druid ',
  'Ettercap ',
  'Giant Boar ',
  'Giant Constrictor',
  'Snake ',
  'Giant Elk ',
  'Gnoll Pack Lord ',
  'Grick ',
  'Grung Elite',
  'Warrior ',
  'Guard Drake ',
  'Hobgoblin Iron',
  'Shadow ',
  'Lizardfolk Shaman ',
  'Meenlock ',
  'Ogre ',
  'Orc Eye of',
  'Gruumsh ',
  'Orc Hand of',
  'Yurtrus ',
  'Orog ',
  'Pegasus ',
  'Shadow Mastiff ',
  'Swarm of',
  'Poisonous Snakes ',
  'Vegepygmy Chief ',
  'Wererat ',
  'Will-o-wisp ',
  'Yuan-ti',
  'Broodguard ',
  'Displacer Beast ',
  'Flail Snail',
  'Green Hag ',
  'Hobgoblin Captain ',
  'Orc Red Fang of',
  'Shargaas',
  'Owlbear ',
  'Phase Spider ',
  'Redcap ',
  'Vampiric Mist',
  'Veteran ',
  'Werewolf ',
  'Yuan-ti Malison ',
  'Banshee ',
  'Barghest ',
  'Couatl ',
  'Girallon ',
  'Gnoll Fang of',
  'Yeenoghu ',
  'Hobgoblin Devastator ',
  'Iron Cobra ',
  'Orc Blade of Ilneval ',
  'Stone Defender ',
  'Wereboar ',
  'Weretiger ',
  'Yeth Hound ',
  'Gorgon ',
  'Oaken Bolter ',
  'Revenant ',
  'Shambling Mound ',
  'Troll ',
  'Werebear ',
  'Wood Woad ',
  'Yuan-ti Pit Master ',
  'Hobgoblin',
  'Warlord ',
  'Annis Hag ',
  'Chimera ',
  'Cyclops ',
  'Wyvern ',
  'Giant Ape ',
  'Grick Alpha ',
  'Korred ',
  'Lost Sorrowsworn ',
  'Oni ',
  'Shadow Dancer ',
  'Venom Troll ',
  'Yuan-ti',
  'Abomination ',
];
const grassland = [
  'Cat ',
  'Deer ',
  'Eagle ',
  'Goat ',
  'Hyena ',
  'Jackal ',
  'Vulture ',
  'Lizard ',
  'Blood Hawk ',
  'Flying Snake ',
  'Giant Weasel ',
  'Guard ',
  'Poisonous Snake ',
  'Stirge ',
  'Tribal Warrior ',
  'Cultist ',
  'Axe Beak ',
  'Boar ',
  'Elk ',
  'Giant Poisonous',
  'Snake ',
  'Giant Wolf Spider ',
  'Gnoll Witherling ',
  'Goblin ',
  'Panther ',
  'Riding Horse ',
  'Wolf ',
  'Cockatrice ',
  'Giant Goat ',
  'Giant Wasp ',
  'Gnoll ',
  'Gnoll Hunter',
  'Hobgoblin ',
  'Jackalwere ',
  'Orc ',
  'Orc Nurtured One of',
  'Yurtrus',
  'Scout ',
  'Swarm of Insects ',
  'Worg ',
  'Bronze Scout ',
  'Bugbear ',
  'Giant Eagle ',
  'Giant Hyena ',
  'Giant Vulture',
  'Gnoll Flesh',
  'Gnawer ',
  'Goblin Boss ',
  'Hippogriff ',
  'Meazel ',
  'Thri-keen ',
  'Ankheg ',
  'Aurochs',
  'Centaur ',
  'Druid ',
  'Giant Boar ',
  'Giant Elk ',
  'Gnoll Pack Lord ',
  'Griffon ',
  'Hobgoblin Iron',
  'Shadow',
  'Ogre ',
  'Ogre Bolt',
  'Launcher',
  'Ogre Howday',
  'Orc Eye of',
  'Gruumsh ',
  'Orc Hand of',
  'Yurtrus',
  'Orog ',
  'Pegasus ',
  'Sabre-toothed',
  'Tiger ',
  'Bandit Captain ',
  'Hobgoblin Captain ',
  'Leucrotta ',
  'Manticore ',
  'Ogre Chain Brute ',
  'Phase Spider ',
  'Sword Wraith',
  'Warrior ',
  'Vampiric Mist ',
  'Veteran ',
  'Barghest ',
  'Couatl ',
  'Gnoll Fang of',
  'Yeenoghu ',
  'Hobgoblin',
  'Devastator ',
  'Iron Cobra ',
  'Ogre Battering Ram ',
  'Orc Blade of Ilneval ',
  'Stone Defender ',
  'Wereboar ',
  'Yeth Hound ',
  'Bulette ',
  'Gorgon ',
  'Oaken Bolter ',
  'Chimera ',
  'Cyclops ',
  'Hobgoblin Warlord ',
  'Mouth of Grolantor ',
];
const hills = [
  'Baboon ',
  'Deer ',
  'Eagle ',
  'Goat ',
  'Hyena ',
  'Raven ',
  'Vulture ',
  'Lizard ',
  'Bandit ',
  'Blood Hawk ',
  'Boggle ',
  'Giant Weasel ',
  'Guard ',
  'Kobold ',
  'Mastiff ',
  'Neogi Hatchling ',
  'Poisonous Snake ',
  'Stirge ',
  'Tribal Warrior ',
  'Xvart ',
  'Axe Beak ',
  'Boar ',
  'Giant Wolf Spider ',
  'Gnoll Witherling ',
  'Goblin ',
  'Kobold Inventor ',
  'Panther ',
  'Pseudodragon ',
  'Swarm of Bats ',
  'Swarm of Ravens ',
  'Winged Kobold ',
  'Wolf ',
  'Firenewt Warrior ',
  'Giant Goat ',
  'Gnoll ',
  'Gnoll Hunter ',
  'Hobgoblin ',
  'Orc ',
  'Orc Nurtured One of',
  'Yurtrus ',
  'Scout ',
  'Swarm of Insects ',
  'Worg ',
  'Brown Bear ',
  'Bugbear ',
  'Dire Wolf ',
  'Giant Eagle ',
  'Giant Hyena ',
  'Goblin Boss ',
  'Half-ogre ',
  'Harpy ',
  'Hippogriff ',
  'Fire Snake ',
  'Bronze Scout ',
  'Meazel ',
  'Firenewt Warlock ofImix',
  'Giant Strider',
  'Gnoll Flesh Gnawer',
  'Kobold',
  'Dragonshield',
  'Kobold Scale',
  'Sorcerer',
  'Nilbog',
  'Xvart Warlock of',
  'Raxivort',
  'Ogre',
  'Giant Boar ',
  'Giant Elk ',
  'Gnoll Pack Lord ',
  'Griffon ',
  'Orog ',
  'Pegasus ',
  'Peryton ',
  'Quetzalcoatlus ',
  'Ogre Howdah',
  'Ogre Bolt',
  'Launcher',
  'Shadow Mastiff',
  'Orc Hand of',
  'Yurtrus ',
  'Hobgoblin Iron',
  'Shadow ',
  'Aurochs ',
  'Green Hag ',
  'Hobgoblin Captain ',
  'Manticore ',
  'Neogi ',
  'Ogre Chain Brute',
  'Orc Red Fang of',
  'Shargaas ',
  'Phase Spider ',
  'Redcap ',
  'Werewolf ',
  'Veteran ',
  'Barghest ',
  'Ettin ',
  'Gnoll Fang of',
  'Yeenoghu ',
  'Hobgoblin',
  'Devastator ',
  'Iron Cobra ',
  'Neogi Master ',
  'Ogre Battering Ram',
  'Orc Blade of Ilneval ',
  'Stone Defender ',
  'Wereboar ',
  'Yeth Hound ',
  'Bulette ',
  'Gorgon ',
  'Hill Giant ',
  'Oaken Bolter ',
  'Revenant ',
  'Tanarukk ',
  'Troll ',
  'Werebear ',
  'Annis Hag ',
  'Chimera ',
  'Cyclops ',
  'Galeb Duhr ',
  'Hobgoblin Warlord ',
  'Mouth of Grolantor ',
  'Stone Giant ',
  'Young Copper',
  'Dragon ',
];
const mountainstOrIce = [
  'Goat ',
  'Owl ',
  'Eagle ',
  'Hawk ',
  'Blood Hawk ',
  'Guard ',
  'Kobold ',
  'Stirge ',
  'Tribal Warrior ',
  'Young Kruthik ',
  'Aarakocra ',
  'Derro ',
  'Kobold Inventor ',
  'Pseudodragon ',
  'Star Spawn Grue ',
  'Winged Kobold ',
  'Firenewt Warrior ',
  'Giant Goat ',
  'Orc ',
  'Ice Mephit ',
  'Orc Nurtured One',
  'of Yurtrus ',
  'Bronze Scout',
  'Brown Bear ',
  'Duergar',
  'Soulblade',
  'Firenewt',
  'Warlock of Imix ',
  'Giant Eagle ',
  'Giant Strider ',
  'Gnoll Flesh',
  'Gnawer ',
  'Half Ogre ',
  'Harpy ',
  'Hippogriff ',
  'Kobold',
  'Dragonshield ',
  'Kobold Scale',
  'Sorcerer ',
  'Adult Kruthik ',
  'Aurochs ',
  'Bandit Captain ',
  'Berserker ',
  'Duergar',
  'Hammerer ',
  'Duergar',
  'Kavalrachni ',
  'Duergar Mind',
  'Master ',
  'Duergar Stone',
  'Guard ',
  'Duergar Xarrorn ',
  'Giant Elk ',
  'Griffon ',
  'Guard Drake ',
  'Ogre ',
  'Ogre Bolt',
  'Launcher ',
  'Ogre Howdah ',
  'Orc Claw of',
  'Luthic ',
  'Orog ',
  'Peryton ',
  'Polar Bear ',
  'Saber-toothed',
  'Tiger ',
  'Basilisk ',
  'Duergar',
  'Screamer ',
  'Hell Hound ',
  'Manticore ',
  'Ogre Chain',
  'Brute ',
  'Orc Red Fang of',
  'Shargaas ',
  'Vampiric Mist ',
  'Veteran ',
  'Winter Wolf ',
  'Yeti ',
  'Barghest ',
  'Ettin ',
  'Iron Cobra ',
  'Ogre Battering',
  'Ram ',
  'Orc Blade of',
  'Ilneval ',
  'Stone Defender ',
  'Air Elemental ',
  'Bulette ',
  'Kruthik Hive Lord ',
  'Oaken Bolter ',
  'Revenant ',
  'Tanarukk ',
  'Troll ',
  'Werebear ',
  'Young Remorhaz ',
  'Umber Hulk ',
  'Annis Hag ',
  'Chimera ',
  'Cyclops ',
  'Duergar Warlord ',
  'Galeb Duhr ',
  'Mammoth ',
  'Wyvern ',
  'Young White',
  'Dragon ',
  'Bheur Hag ',
  'Lost',
  'Sorrowsworn ',
  'Stone Giant ',
];
const swamp = [
  'Rat ',
  'Raven ',
  'Frog ',
  'Spider ',
  'Giant Rat ',
  'Kobold ',
  'Poisonous Snake ',
  'Stirge ',
  'Tribal Warrior ',
  'Bullywug ',
  'Constrictor Snake ',
  'Giant Frog ',
  'Giant Lizard ',
  'Giant Poisonous',
  'Snake ',
  'Mud Mephit ',
  'Oblex Spawn',
  'Star Spawn Grue',
  'Swarm of Ravens ',
  'Vegepygmy',
  'Winged Kobold ',
  'Wretched',
  'Sorrowsworn',
  'Crocodile ',
  'Darkling ',
  'Lizardfolk ',
  'Orc ',
  'Scout ',
  'Skulk',
  'Swarm of Insects ',
  'Swarm of Rot',
  'Grubs ',
  'Ghoul ',
  'Giant Spider ',
  'Giant Toad ',
  'Meazel ',
  'Thorny ',
  'Vargouille ',
  'Yuan-ti Pureblood ',
  'Bugbear ',
  'Darkling Elder ',
  'Ghast ',
  'Giant Constrictor',
  'Snake ',
  'Guard Drake ',
  'Lizardfolk Shaman ',
  'Meenlock ',
  'Ogre ',
  'Orc Eye of Gruumsh ',
  'Shadow Mastiff ',
  'Swarm of Poisonous',
  'Snakes ',
  'Vegepygmy Chief ',
  'Will-o-wisp ',
  'Flail Snail ',
  'Green Hag ',
  'Redcap ',
  'Sword Wraith',
  'Warrior ',
  'Vampiric Mist ',
  'Wight ',
  'Yuan-ti Malison ',
  'Bugbear Chief ',
  'Chuul ',
  'Ghost ',
  'Lizard King / Queen ',
  'Orc War Chief ',
  'Wereboar ',
  'Yuan-ti Mind',
  'Whisperer ',
  'Adult Oblex ',
  'Allip ',
  'Catoblepas ',
  'Giant Crocodile ',
  'Revenant ',
  'Shambling Mound ',
  'Troll ',
  'Water Elemental ',
  'Bodak ',
  'Annis Hag ',
  'Chimera ',
  'Hobgoblin Warlord ',
  'Lost',
  'Sorrowsworn ',
  'Maurezhi ',
  'Venom Troll ',
  'Young Black',
  'Dragon ',
  'Yuan-ti',
  'Abomination ',
];
const urban = [
  'Rat ',
  'Raven ',
  'Frog ',
  'Spider ',
  'Bandit ',
  'Boggle ',
  'Cultist ',
  'Flying Snake ',
  'Giant Rat ',
  'Guard ',
  'Kobold ',
  'Mastiff ',
  'Mule ',
  'Noble ',
  'Pony ',
  'Stirge ',
  'Acolyte ',
  'Draft Horse ',
  'Giant Centipede ',
  'Giant Poisonous',
  'Snake ',
  'Kenku ',
  'Kobold Inventor ',
  'Oblex Spawn ',
  'Ox ',
  'Pseudodragon ',
  'Riding Horse ',
  'Skeleton ',
  'Smoke Mephit ',
  'Swarm of Bats ',
  'Swarm of Rats ',
  'Swarm of',
  'Ravens ',
  'Winged Kobold ',
  'Wretched',
  'Sorrowsworn ',
  'Zombie ',
  'Goblin ',
  'Giant Wolf',
  'Spider ',
  'Crocodile ',
  'Darkling ',
  'Giant Wasp ',
  'Shadow ',
  'Skulk ',
  'Swarm of Insects ',
  'Thug ',
  'Warhorse ',
  'Ghoul ',
  'Giant Spider ',
  'Half Ogre ',
  'Kobold Scale',
  'Sorcerer ',
  'Meazel',
  'Specter ',
  'Spy ',
  'Stone Cursed',
  'Yuan-ti Pureblood ',
  'Animated Armour ',
  'Bandit Captain ',
  'Cult Fanatic ',
  'Gargoyle ',
  'Darkling Eldet ',
  'Ghast ',
  'Guard Drake ',
  'Meenlock ',
  'Priest ',
  'Mimic ',
  'Wererat ',
  'Will o’ Wisp ',
  'Rug of Smothering ',
  'Doppelganger ',
  'Giff ',
  'Knight ',
  'Orc Red Fang of',
  'Shargaas ',
  'Phase Spider ',
  'Slithering Tracker ',
  'Vampiric Mist ',
  'Veteran ',
  'Water Weird ',
  'Wight ',
  'Babau ',
  'Couatl ',
  'Deathlock ',
  'Dybbuk ',
  'Ghost ',
  'Incubus ',
  'Succubus ',
  'Orc Blade of',
  'Ilneval ',
  'Adult Oblex ',
  'Allip ',
  'Banderhobb ',
  'Cambion ',
  'Gladiator ',
  'Revenant ',
  'Swarm of Cranium',
  'Rats ',
  'Vampire Spawn ',
  'Bodak ',
  'Invisible Stalker ',
  'Mage ',
  'White Abishai ',
  'Black Abishai ',
  'Lost',
  'Sorrowsworn ',
  'Maurezhi ',
  'Oni ',
  'Shadow Dancer ',
  'Shield Guardian ',
];

const tablesTable: { [index: string]: string[] } = {
  aquatic: aquatic,
  coastal: coastal,
  desert: desert,
  dungeon: dungeon,
  forest: forest,
  grassland: grassland,
  hills: hills,
  mountainstOrIce: mountainstOrIce,
  swamp: swamp,
  urban: urban,
};

const table: { [index: string]: { type: string; options?: string[] } } = {
  type: {
    type: 'select',
    options: Object.keys(tablesTable),
  },
};
const GenName = 'Monsters';

export const MonstersGenerator = (fields: any) => {
  const [[type]] = fields;
  const table = tablesTable[type];
  return table[random(1, table.length) - 1];
};

export const Monsters = ({
  writeToLog,
}: {
  writeToLog: (result: string) => void;
}) => {
  return DefaultCombinedGenerator({
    table,
    GenName,
    generator: MonstersGenerator,
    writeToLog,
  });
};
