export const randomEncounters = [
  'Something happens To you',
  'Something happens To someone else',
  'Something happens To the environment',
  'Something happens To a creature',
  'Something happens Supernatural / Metaphysical',
  'You sense something Mentally/psychically',
  'You sense something Physically (heat/cold/vibration)',
  'You sense something Supernatural / Metaphysical',
  'You smell something Horrific',
  'You smell something Pleasant',
  'You smell something Weird',
  'You see an occurrence Involving the environment',
  'You see an occurrence Involving other creatures',
  'You see an occurrence Supernatural',
  'You hear something Involving the environment',
  'You hear something Involving other creatures',
  'You hear something Supernatural',
  'You find something Architecture / Feature',
  'You find something Item / NPC',
  'You find something Clue / trail / monster sign/ writing',
];
