import { randomEncounters } from './randomEncounters';

export const Wild_Encounters_Table = [
  'Small dungeon or crypt found. Purpose and history unknown. If entering, go to Chapter 8: Random Dungeon Generation.',
  'Small dungeon or crypt found. Purpose and history unknown. If entering, go to Chapter 8: Random Dungeon Generation.',
  'Small dungeon or crypt found. Purpose and history unknown. If entering, go to Chapter 8: Random Dungeon Generation.',
  'Small dungeon or crypt found. Purpose and history unknown. If entering, go to Chapter 8: Random Dungeon Generation.',
  'Ready-made camp found, or cosy cave, that could potentially be used as shelter for the night, or a base while exploring. Inhabited?',
  'A small creek, babbling pleasantly. Or a large crack, bubbling pungently.',
  'A storm on the horizon, lightning dancing underneath dark grey clouds.',
  'A sinkhole has opened up nearby.',
  'Abandoned, empty town.',
  'NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not choose to accept',
  'NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not choose to accept',
  'NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not choose to accept',
  'NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not choose to accept',
  'NPC met, who gives PC information about possible quest. Go to Chapter 7 and generate a quest, which you may or may not choose to accept',
  'Abandoned campsite found. Use Q/A rolls to find out more.',
  'A tree with what looks like Druid markings.',
  'You find survivors of some sort of attack, and they have a tale to tell...',
  'Plundered barrow / burial mound. But did they get everything? And what still waits there? (50% mostly empty)',
  'On the road, a dropped item. A backpack, a purse with interesting contents / a hat with a note tucked inside / an engraved ring… could be anything. Use Q/A roll to find out details.',
  'Interesting traveller. This character has obviously seen some things...',
  'Cemetery. Some of the graves have been looted, and most of the tombstones are so old that the names have worn off.',
  'Prisoner(s) being escorted in a heavily-armoured cart.',
  'Interesting geological feature. Use Q/A mechanic to find out what.',
  'You find a discarded backpack with some intriguing contents.',
  'An odd noise is coming from some distance ahead...',
  'Strange lights in the nearby hills are attracting your attention.',
  'You stumble across an orchard, filled with ripe and delicious fruit. The owner is nowhere in sight',
  'Bounty hunters, searching for a fugitive. “You seen anyone?” (Who they are working for is unclear)',
  'Sudden and abrupt change in weather',
  'Abandoned mine, dwarven or otherwise.',
  'You hear howling in the distance. It could be wolves, but the sound is strange somehow...',
  'Debris from a recent, large battle. Who fought here, and who won? How recent was this?',
  'Humanoid corpse. 25% yoiu find a clue (see Clue table in Chapter 9).',
  'A bird (or some other creature – roll Creature Table Chapter 14) begins talking to you, in fluent Common! And not just mindless parroting...',
  'A royal/noble personage and their entourage passes in an opulent carriage.',
  'A flock of birds (vultures? ravens?) circles over a point somewhere overhead',
  'You find an old, ruined monument. Is it to a god, a famous local figure, or something else?',
  'A traveller with information/warning about a situation in the next settlement.',
  'Unmarked settlement: town/village/hamlet. Human?',
  'You reach a bridge over a small river. The bridge is washed out. Travellers are waiting here, unsure what to do.',
  'You find an injured beast',
  'A farmer invites you into his house for a meal, and possibly some of his home brew ale/mead as well',
  'Overturned/broken-down cart. Is it attended?',
  'Monster ambush. Level-appropriate easy encounter. Go to Chapter 16.',
  'Monster ambush. Level-appropriate easy encounter. Go to Chapter 16.',
  'Monster ambush. Level-appropriate easy encounter. Go to Chapter 16.',
  'Monster ambush. Level-appropriate easy encounter. Go to Chapter 16.',
  'Monster ambush. Level-appropriate easy encounter. Go to Chapter 16.',
  'An animal wanders across your path. It glances up at you but doesn’t seem particularly bothered by your presence.',
  'Trapped creature (humanoid? monster? What type of trap?)',
  'An abandoned/ruined structure of some kind, which may or may not have a subterranean component',
  'An abandoned/ruined structure of some kind, which may or may not have a subterranean component',
  'An abandoned/ruined structure of some kind, which may or may not have a subterranean component',
  'An old hermit. What’s he babbling about?',
  'A creepy and unsettling token/sign.',
  'Traveling merchant',
  'A traveling adventurer who is impressed and wants to join your party.',
  'Monster Encounter: Level-appropriate medium encounter. Go to Chapter 16.',
  'Monster Encounter: Level-appropriate medium encounter. Go to Chapter 16.',
  'Monster Encounter: Level-appropriate medium encounter. Go to Chapter 16.',
  'Monster Encounter: Level-appropriate medium encounter. Go to Chapter 16.',
  'Monster Encounter: Level-appropriate medium encounter. Go to Chapter 16.',
  'A traveller, resting by the side of the road, begins pointing and laughing uproariously at you. Is she mad?',
  'Heavily-guarded transport passes.',
  'Travelling sage/archivist',
  'Bandits (human or otherwise) demand a toll from you.',
  'Monster: Level appropriate hard encounter.',
  'Monster: Level appropriate hard encounter.',
  'Monster: Level appropriate hard encounter.',
  'Monster: Level appropriate hard encounter.',
  'Monster: Level appropriate hard encounter.',
  'A starving family begging for food or gold',
  'A tribe who owns the land demands a tribute from you for passage (and in return will escort you through – whether you like it or not).',
  'A travelling troupe of performers (80% Friendly)',
  'A travelling merchant, but his wares are not the ordinary. Indeed, much of it is illegal in some way. Is he a smuggler? A drug dealer? A heist thief?',
  'Hunters/travellers/adventurers. Camped up and relaxing.',
  'You see a low rocky hill, where faces have been carved into the rocks, along with the shapes of various beasts. It is artfully done, and seems to tell some sort of story.',
  'You see a track leading away from the road and into the forest/hills. Who knows where it leads...',
  'Bandits waylay you and demand all your money',
  'On a lonely stretch of road, you see a lone cabin, but cannot tell if it is inhabited or not',
  'A long-forgotten battlefield. How many died here?',
  'A tower, visible off the road some distance.',
  'Patrol from the nearest settlement',
  'Unmarked settlement',
  'The road disappears and the place looks nothing like on the map.',
  'NPC appears with quest. (Use Chapter 7).',
  'NPC appears with quest. (Use Chapter 7).',
  'NPC appears with quest. (Use Chapter 7).',
  'NPC appears with quest. (Use Chapter 7).',
  'NPC appears with quest. (Use Chapter 7).',
  'Monster! Level-appropriate encounter. 1-3: Hard, 4: Deadly',
  'Monster! Level-appropriate encounter. 1-3: Hard, 4: Deadly',
  'Monster! Level-appropriate encounter. 1-3: Hard, 4: Deadly',
  'Monster! Level-appropriate encounter. 1-3: Hard, 4: Deadly',
  'Monster! Level-appropriate encounter. 1-3: Hard, 4: Deadly',
];

export const randomWildEncountersTable = [
  'Landslide / Avalanche',
  'Massed Animals',
  'Earthquake',
  'Toll demanded',
  'Storm',
  'Distressed NPC',
  'Druid gathering',
  'Besieged settlement',
  'Religious pilgrimage',
  'Come across structure',
  'Army encamped',
  'Battle in progress',
  'Sudden storm / gale force winds',
  'Beast / Monster carcass',
  'Overturned cart',
  'Monster',
  'easy encounter',
  'Flash flood',
  'Monster',
  'easy encounter',
  'Forest Fire',
  'Monster',
  'medium encounter',
  'Local humanoids having a festival',
  'Monster',
  'medium encounter',
  'Solar eclipse',
  'Monster',
  'hard encounter',
  'Hail (large hailstones?)',
  'Monster',
  'deadly encounter',
  'Hurricane',
  'Volcanic eruption',
  'Tribal encounter',
  'Plague (insect / vermin)',
  'Animal stampede',
  'Interdimensional Rift',
  'Tree falls',
  'Army going to war',
  'Boulder falls',
  'Sinkhole Appears',
  'Unseasonable weather',
  'Appearance of Tyrant in the area',
  'Lightning strikes',
  'Savage raiding party',
  'Market',
  'Marauding monster attacking village',
  'Hunting Party',
  'Undead awakening',
  'Farmers harvesting crops',
  'Cart passing',
  'Unmarked Settlement',
  'Refugees',
  ...randomEncounters,
];
