import { armorSchema } from '..';

export const sandals: armorSchema = {
  techLevel: 2,
  code: 'sandals',
  zones: [['leftFoot'], ['rightFoot']],
  matchingArmorTypes: [
    'clothordinary1',
    'clothordinary2',
    'clothordinary3',
    'clothordinary4',
    'clothordinary5',
    'clothordinary6',
    'clothordinary7',
    'clothordinary8',
    'clothordinary-2',
    'clothordinary-1',
    'clothordinary0',
    'clothsummer1',
    'clothsummer2',
    'clothsummer3',
    'clothsummer4',
    'clothsummer5',
    'clothsummer6',
    'clothsummer7',
    'clothsummer8',
    'clothsummer0',
    'clothsummer-2',
    'clothsummer-1',
    'clothwinter0',
    'clothwinter1',
    'clothwinter2',
    'clothwinter3',
    'clothwinter4',
    'clothwinter5',
    'clothwinter6',
    'clothwinter7',
    'clothwinter8',
    'clothwinter-2',
    'clothwinter-1',
    'wood',
    'straw',
    'layeredLeatherLight',
    'leatherMedium',
    'layeredLeatherMedium',
  ],
};
